### ISSUE TITLE
Can not use simulator on the intel paltform

### ISSUE THREAD

**Issue by shalom-aviv** [livekit/client-example-swift#10]
Hi 

Is it possible to return the possibility to run this example on the Intel simulator?

Thank you

**Comment by iankoex** [comment]
what do you mean?

**Comment by shalom-aviv** [comment]
I found **arm64** in ARCHS options and changed it to "Standard arch..."

After that i can launch sample app inside intel simulator.

<img width="1493" alt="Screenshot 2022-09-18 at 12 50 04" src="https://user-images.githubusercontent.com/78256107/190896255-4cf6d361-1d5c-4187-89a0-5ba7169856bc.png">

**Comment by shalom-aviv** [comment]
check last comment
