### ISSUE TITLE
Could you please give advice how implement routing to diff audio devices?

### ISSUE THREAD

**Issue by shalom-aviv** [livekit/client-example-swift#11]
Hey

How I can route audio to dynamics, headphone, speaker?

Thank you

**Comment by davidzhao** [comment]
are you referring to iOS or Mac? They look quite a bit different.

On iOS, audio output is highly restrictive and Apple controls audio routing via AudioSession APIs. LiveKit will set defaults, but allows user to override by setting [onShouldConfigureAudioSession](https://docs.livekit.io/client-sdk-swift/LiveKit/#livekit.onshouldconfigureaudiosession)

(closing this as it's not an issue)

**Comment by shalom-aviv** [comment]
> are you referring to iOS or Mac? They look quite a bit different.
> 
> On iOS, audio output is highly restrictive and Apple controls audio routing via AudioSession APIs. LiveKit will set defaults, but allows user to override by setting [onShouldConfigureAudioSession](https://docs.livekit.io/client-sdk-swift/LiveKit/#livekit.onshouldconfigureaudiosession)
> 
> (closing this as it's not an issue)

to iOs
