### ISSUE TITLE
Can't connect to LiveKit room with TURN servers

### ISSUE THREAD

**Issue by janoskranczler** [livekit/client-example-swift#13]
Hi!

I tried to connect to a LiveKit room with TURN servers. I changed the `RoomContext.connect` method to configure the servers:
```swift
        let rtcConfiguration = RTCConfiguration()
        rtcConfiguration.iceServers = [
            RTCIceServer(
                urlStrings: [
                    "turn:*********?transport=udp",
                    "turns::*********:443?transport=tcp"
                ],
                username: ":*********",
                credential: ":*********"
            )
        ]

        let connectOptions = ConnectOptions(
            autoSubscribe: !publish && autoSubscribe, // don't autosubscribe if publish mode
            rtcConfiguration: rtcConfiguration,
            publishOnlyMode: publish ? "publish_\(UUID().uuidString)" : nil
        )
```

But when I tried to connect with the example app I got the following error message:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/6105557/211323689-83f7d27c-3c77-4970-82a7-b85ed477a70a.png">

When I try to connect to a room that doesn't require TURN, it works.

**Comment by janoskranczler** [comment]
I've found the root of the issue and created a PR:
https://github.com/livekit/client-sdk-swift/pull/174

**Comment by hiroshihorie** [comment]
@janoskranczler Thanks for the PR !, It has been merged so I'll close this one.
